apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: todo-schema
  name: todo-schema
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-schema
  template:
    metadata:
      labels:
        app: todo-schema
    spec:
      containers:
      - name: todo-schema
        image: docker.io/burrsutter/todo:6.0.0
        imagePullPolicy: Always
        env:
        - name: QUARKUS_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/postgresdb
        - name: QUARKUS_DATASOURCE_USERNAME
          value: admin
        - name: QUARKUS_DATASOURCE_PASSWORD
          value: adminS3cret
        - name: QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION
          value: drop-and-create
        ports:
          - containerPort: 8080
        resources:
          requests: 
            memory: "40Mi" 
            cpu: "100m" 
          limits:
            memory: "80Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
              port: 8080
              path: /
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 2          
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 3

